"""Audit action names (spec section 24)."""

from enum import StrEnum


class AuditAction(StrEnum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    REGISTER = "REGISTER"
    ACCOUNT_APPROVED = "ACCOUNT_APPROVED"
    ACCOUNT_REJECTED = "ACCOUNT_REJECTED"
    USER_UPDATED = "USER_UPDATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_DELETED = "USER_DELETED"
    ROLE_CHANGED = "ROLE_CHANGED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_APPROVED = "DOCUMENT_APPROVED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    DOCUMENT_UPDATED = "DOCUMENT_UPDATED"
    CHAT_QUERY = "CHAT_QUERY"
    DATA_ACCESS = "DATA_ACCESS"
    AUDIT_EXPORTED = "AUDIT_EXPORTED"
